export const AST_TYPES = {
    "Program": "Program",
    "ExpressionStatement": "ExpressionStatement",
    "BlockStatement": "BlockStatement",
    "IfStatement": "IfStatement",
    "WhileStatement": "WhileStatement",
    "ForStatement": "ForStatement",
    "FunctionDeclaration": "FunctionDeclaration",
    "ReturnStatement": "ReturnStatement",
    "CallExpression": "CallExpression",
    "VariableDeclaration": "VariableDeclaration",
    "VariableExpression": "VariableExpression",
    "AssignmentExpression": "AssignmentExpression",
    "BinaryExpression": "BinaryExpression",
    "UnaryExpression": "UnaryExpression",
    "LiteralExpression": "LiteralExpression",
    "GroupingExpression": "GroupingExpression",
    "LogicalExpression": "LogicalExpression",
    "MemberExpression": "MemberExpression",
    "Identifier": "Identifier"
}