export class Token {
    constructor(type, value = null, line, column) {
        this.type = type;
        this.value = value;
        this.line = line;
        this.column = column;
    }
}

export const TokenType = {
    "DOT": "DOT",
    EOF: 'EOF',
    KEYWORD: "KEYWORD",
    WHITESPACE: 'WHITESPACE',
    NEWLINE: 'NEWLINE',
    IDENTIFIER: 'IDENTIFIER',
    STRING: 'STRING',
    NUMBER: 'NUMBER',
    COMMA: 'COMMA',
    COLON: 'COLON',
    SEMICOLON: 'SEMICOLON',
    LBRACKET: 'LBRACKET',
    RBRACKET: 'RBRACKET',
    LPAREN: 'LPAREN',
    RPAREN: 'RPAREN',
    LBRACE: 'LBRACE',
    RBRACE: 'RBRACE',
    PLUS: 'PLUS',
    MINUS: 'MINUS',
    STAR: 'STAR',
    SLASH: 'SLASH',
    PERCENT: 'PERCENT',
    BANG: 'BANG',
    BANG_EQUAL: 'BANG_EQUAL',
    EQUAL_EQUAL: 'EQUAL_EQUAL',
    LESS_EQUAL: 'LESS_EQUAL',
    GREATER_EQUAL: 'GREATER_EQUAL',
    EQUAL: 'EQUAL',
    AND: 'AND',
    OR: 'OR',
    NOT: 'NOT',
    IF: 'IF',
    ELSE: 'ELSE',
    WHILE: 'WHILE',
    FOR: 'FOR',
    RETURN: 'RETURN',
    FUNCTION: 'FUNCTION',
    TRUE: 'TRUE',
    FALSE: 'FALSE',
    NULL: 'NULL',
    BREAK: 'BREAK',
    CONTINUE: 'CONTINUE',
    NEW: 'NEW',
    DELETE: 'DELETE',
    THIS: 'THIS',
    CLASS: 'CLASS',
    EXTENDS: 'EXTENDS',
    SUPER: 'SUPER',
    CONST: 'CONST',
    LET: 'LET',
    VAR: 'VAR',
    IF_ELSE: 'IF_ELSE',
    FOR_IN: 'FOR_IN',
    FOR_OF: 'FOR_OF',
    FOR_EACH: 'FOR_EACH',
    SWITCH: 'SWITCH',
    CASE: 'CASE',
    DEFAULT: 'DEFAULT',
    TRY: 'TRY',
    CATCH: 'CATCH',
    FINALLY: 'FINALLY',
    THROW: 'THROW',
}